### ISSUE TITLE
Failed to activate the autocomplete-go package

### ISSUE THREAD

**Issue by kyla963** [joefitzgerald/autocomplete-go#36]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [autocomplete-go](https://github.com/joefitzgerald/autocomplete-go) package, v1.1.0
### Stack Trace

Failed to activate the autocomplete-go package

```
At Unexpected token .

SyntaxError: Unexpected token .
    at Module._compile (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/Users/kylacross/.atom/packages/autocomplete-go/lib/main.js:16:5)
    at Package.module.exports.Package.activateNow (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Users/kylacross/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-go, v1.1.0
builder-go, v1.0.0
darwin_amd64, vundefined
github-utils, v1.5.0
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.14
navigator-godef, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by pbnj** [comment]
I assume you were trying to install `go-plus`.

I got a similar issue when I was installing `go-plus` and was able to resolve it by uninstalling the automatically-installed Go packages and reinstalling `go-plus` atom package.

Turns out, I previously had some of these plugins individually installed prior to attempting to install `go-plus`.
